server.port=8082
spring.application.name=HOTEL-SERVICE

spring.datasource.url=jdbc:mysql://localhost:3306/hotels_db
spring.datasource.username=root
spring.datasource.password=2401301024
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Swagger URL customize karo
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
# Cloudinary config
cloudinary.cloud-name=root
cloudinary.api-key=519364271714163
cloudinary.api-secret=AyzcD7OCgCVOfU4Z2xNFPhdSzpA